name = "rhino-remote-mcp-authless"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "RHINO_WS", class_name = "RhinoWebSocketDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["RhinoWebSocketDO"]

[triggers]
crons = [] 